package com.laozhang.struts2.admin.model;

import java.sql.Timestamp;

import com.laozhang.struts2.base.model.BaseObject;

public class UserInfo extends BaseObject {
	private static final long serialVersionUID = 1L;

	private Long id;
	
	private String userId;
	
	private String password;
	
	private String name;
	
	private String sex;
	
	private String tel;
	
	private String email;
	
	private String orgId;
	
	private String orgType;
	
	private String recsts;
	
	private Timestamp lastTime;
	
	private String orgName;
	
	private Long roleId;
	
	private String roleDesc;
	
	
	public Long getId()
	{
		return id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	public String getSex()
	{
		return sex;
	}

	public void setSex(String sex)
	{
		this.sex = sex;
	}

	public String getTel()
	{
		return tel;
	}

	public void setTel(String tel)
	{
		this.tel = tel;
	}

	public String getEmail()
	{
		return email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getOrgId()
	{
		return orgId;
	}

	public void setOrgId(String orgId)
	{
		this.orgId = orgId;
	}

	public String getOrgType()
	{
		return orgType;
	}

	public void setOrgType(String orgType)
	{
		this.orgType = orgType;
	}

	public String getRecsts()
	{
		return recsts;
	}

	public void setRecsts(String recsts)
	{
		this.recsts = recsts;
	}

	public Timestamp getLastTime() {
		return lastTime;
	}

	public void setLastTime(Timestamp lastTime) {
		this.lastTime = lastTime;
	}

	public String getUserId()
	{
		return userId;
	}

	public void setUserId(String userId)
	{
		this.userId = userId;
	}

	public String getPassword()
	{
		return password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	public String getName()
	{
		return name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public String getRoleDesc() {
		return roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}
	
	/*
	  
	  CREATE TABLE "USER_INFO" (
  "ID"	BIGINT	NOT NULL	GENERATED BY DEFAULT
    AS IDENTITY (START WITH 1, INCREMENT BY 1, CACHE 20,
       NO MINVALUE, NO MAXVALUE, NO CYCLE, NO ORDER),
  "USER_ID"	VARCHAR(20),
  "PASSWORD"	VARCHAR(100),
  "NAME"	VARCHAR(80),
  "SEX"	CHARACTER(1),
  "TEL"	VARCHAR(20),
  "EMAIL"	VARCHAR(100),
  "ORG_ID"	CHARACTER(12),
  "RECSTS"	CHARACTER(1),
  "ORG_TYPE"	VARCHAR(1),
  "LAST_TIME"	TIMESTAMP,
  CONSTRAINT PRIMARY KEY "ID"
) 
	  
	  */

}
